################################################################################
# H-Village Dormitory Survey Analysis: Complete Publication-Quality Analysis
# FINAL VERSION - Figure Numbers Match Manuscript Order
# 
# Figure 1: Dormitory Photos (NOT generated by R - manual insertion)
# Figure 2: Building Cultural Effect Estimation (ICC, Bootstrap, PCoA)
# Figure 3: Cultural Convergence Analysis
# Figure 4: Gender Influence Detailed Analysis (4-panel)
# Figure 5: Building Type Comparison (Q5, Q8, Co-ed)
# Figure 6: Q2 Opposite-Sex Communication Barrier Analysis
# Figure 7: Building Type Overview
################################################################################

# ==============================================================================
# SECTION 0: Package Installation and Loading
# ==============================================================================

required_packages <- c(
  "tidyverse", "dplyr", "tidyr", "readr", "stringr", "forcats",
  "lme4", "lmerTest", "emmeans", "broom", "broom.mixed", "performance",
  "ggplot2", "ggpubr", "ggsci", "patchwork", "cowplot", "scales", 
  "RColorBrewer", "viridis", "ggridges", "ggdist", "ggsignif",
  "vegan", "compositions", "ape", "FactoMineR", "factoextra",
  "boot", "permute", "car", "reshape2", "gridExtra", "grid", "ggrepel",
  "MuMIn", "arm", "Hmisc"
)

install_if_missing <- function(packages) {
  new_packages <- packages[!(packages %in% installed.packages()[,"Package"])]
  if(length(new_packages) > 0) {
    for(pkg in new_packages) {
      tryCatch({
        install.packages(pkg, repos = "https://cloud.r-project.org/", quiet = TRUE)
      }, error = function(e) message(paste("Could not install", pkg)))
    }
  }
}

install_if_missing(required_packages)

suppressPackageStartupMessages({
  library(tidyverse); library(ggplot2); library(dplyr); library(tidyr)
  library(readr); library(stringr); library(forcats)
  library(lme4); library(lmerTest); library(emmeans); library(broom); library(broom.mixed)
  library(ggpubr); library(ggsci); library(patchwork); library(cowplot)
  library(scales); library(RColorBrewer); library(viridis)
  library(vegan); library(compositions); library(ape)
  library(FactoMineR); library(factoextra)
  library(boot); library(permute); library(car)
  library(reshape2); library(gridExtra); library(grid); library(ggrepel)
})

tryCatch(library(ggridges), error = function(e) message("ggridges not available"))
tryCatch(library(ggdist), error = function(e) message("ggdist not available"))
tryCatch(library(ggsignif), error = function(e) message("ggsignif not available"))
tryCatch(library(performance), error = function(e) message("performance not available"))
tryCatch(library(MuMIn), error = function(e) message("MuMIn not available"))
tryCatch(library(arm), error = function(e) message("arm not available"))
tryCatch(library(Hmisc), error = function(e) message("Hmisc not available"))

library(dplyr)
set.seed(42)

# ==============================================================================
# SECTION 1: Configuration
# ==============================================================================

file_paths <- list(
  "May" = "HMay.csv",
  "June" = "HJune.csv", 
  "July" = "HJuly.csv",
  "October" = "HOctober.csv",
  "November" = "HNovember.csv"
)

# Color palettes
building_colors <- c("Basil" = "#2E8B57", "Turmeric" = "#E69F00", 
                     "Rosemary" = "#9467BD", "Paprika" = "#D62728")
resident_colors <- c("New" = "#4393C3", "Incumbent" = "#D6604D")
gender_colors <- c("Male" = "#3182BD", "Female" = "#E6550D")
building_type_colors <- c("Male-only" = "#3182BD", "Female-only" = "#E6550D", "Co-ed" = "#756BB1")
influence_colors <- c("Same-gender" = "#2166AC", "Opposite-gender" = "#B2182B")
incumbent_gender_colors <- c("Male Incumbent" = "#3182BD", "Female Incumbent" = "#E6550D")

question_labels_short <- c(
  "Q1" = "Communication", "Q2" = "Opp.Sex Barrier", "Q3" = "Unit Friendship",
  "Q4" = "Room Cleanliness", "Q5" = "Event Interest", "Q6" = "Presentation",
  "Q7" = "Self-disclosure", "Q8" = "Bldg Attachment"
)

# ==============================================================================
# SECTION 2: Custom Theme
# ==============================================================================

theme_nature <- function(base_size = 11, base_family = "") {
  theme_minimal(base_size = base_size, base_family = base_family) %+replace%
    theme(
      panel.background = element_rect(fill = "white", color = NA),
      panel.grid.major = element_line(color = "grey92", linewidth = 0.3),
      panel.grid.minor = element_blank(),
      panel.border = element_rect(color = "black", fill = NA, linewidth = 0.5),
      axis.line = element_blank(),
      axis.ticks = element_line(color = "black", linewidth = 0.3),
      axis.text = element_text(color = "black", size = base_size - 1),
      axis.title = element_text(color = "black", size = base_size, face = "bold"),
      legend.background = element_rect(fill = "white", color = NA),
      legend.key = element_rect(fill = "white", color = NA),
      legend.text = element_text(size = base_size - 1),
      legend.title = element_text(size = base_size, face = "bold"),
      strip.background = element_rect(fill = "grey95", color = "black", linewidth = 0.3),
      strip.text = element_text(color = "black", size = base_size, face = "bold"),
      plot.title = element_text(size = base_size + 2, face = "bold", hjust = 0),
      plot.subtitle = element_text(size = base_size, hjust = 0, color = "grey30"),
      plot.tag = element_text(size = base_size + 2, face = "bold"),
      plot.margin = margin(10, 10, 10, 10),
      plot.background = element_rect(fill = "white", color = NA)
    )
}

# ==============================================================================
# SECTION 3: Data Loading
# ==============================================================================

load_survey_data_robust <- function(filepath, month_name) {
  if (!file.exists(filepath)) {
    warning(paste("File not found:", filepath))
    return(NULL)
  }
  
  df <- read_csv(filepath, show_col_types = FALSE)
  cols <- names(df)
  
  find_col <- function(pattern) {
    idx <- which(str_detect(cols, pattern))
    if (length(idx) > 0) return(cols[idx[1]])
    return(NA)
  }
  
  col_international <- find_col("留学生")
  col_building <- find_col("住んでいる棟")
  col_floor <- find_col("何階")
  col_grade <- find_col("学年")
  col_gender <- find_col("性別")
  col_Q1 <- find_col("Q1"); col_Q2 <- find_col("Q2")
  col_Q3 <- find_col("Q3"); col_Q4 <- find_col("Q4")
  col_Q5 <- find_col("Q5"); col_Q6 <- find_col("Q6")
  col_Q7 <- find_col("Q7"); col_Q8 <- find_col("Q8")
  
  result <- data.frame(
    international = as.character(df[[col_international]]),
    building = as.character(df[[col_building]]),
    floor = as.character(df[[col_floor]]),
    grade = as.character(df[[col_grade]]),
    gender = as.character(df[[col_gender]]),
    Q1 = as.numeric(df[[col_Q1]]), Q2 = as.numeric(df[[col_Q2]]),
    Q3 = as.numeric(df[[col_Q3]]), Q4 = as.numeric(df[[col_Q4]]),
    Q5 = as.numeric(df[[col_Q5]]), Q6 = as.numeric(df[[col_Q6]]),
    Q7 = as.numeric(df[[col_Q7]]), Q8 = as.numeric(df[[col_Q8]]),
    month = month_name,
    stringsAsFactors = FALSE
  )
  return(result)
}

cat("=== Loading Data ===\n")
all_data <- NULL
for (month_name in names(file_paths)) {
  month_data <- load_survey_data_robust(file_paths[[month_name]], month_name)
  if (!is.null(month_data)) {
    all_data <- bind_rows(all_data, month_data)
    cat(sprintf("  %s: %d rows loaded\n", month_name, nrow(month_data)))
  } else {
    cat(sprintf("  %s: SKIPPED (file not found)\n", month_name))
  }
}

if (is.null(all_data) || nrow(all_data) == 0) stop("No data loaded!")
cat(sprintf("\nTotal raw data: %d rows\n", nrow(all_data)))

# Clean data
data_clean <- all_data %>%
  dplyr::filter(international == "いいえ") %>%
  dplyr::mutate(
    building = case_when(
      building == "バジル" ~ "Basil", building == "ターメリック" ~ "Turmeric",
      building == "ローズマリー" ~ "Rosemary", building == "パプリカ" ~ "Paprika",
      TRUE ~ building),
    gender = case_when(gender == "男性" ~ "Male", gender == "女性" ~ "Female", TRUE ~ gender),
    grade = case_when(
      grade == "学部1年" ~ "UG1", grade == "学部2年" ~ "UG2", grade == "学部3年" ~ "UG3",
      grade == "学部4年" ~ "UG4", grade == "修士" ~ "Master", grade == "博士" ~ "PhD",
      TRUE ~ grade),
    resident_type = ifelse(grade == "UG1", "New", "Incumbent"),
    building_type = case_when(
      building == "Basil" ~ "Male-only",
      building == "Turmeric" ~ "Female-only",
      building %in% c("Rosemary", "Paprika") ~ "Co-ed",
      TRUE ~ NA_character_
    ),
    coed_subtype = case_when(
      building == "Rosemary" ~ "Same-floor",
      building == "Paprika" ~ "Floor-separated",
      TRUE ~ NA_character_
    ),
    month = factor(month, levels = c("May", "June", "July", "October", "November")),
    month_numeric = as.numeric(month),
    building = factor(building, levels = c("Basil", "Turmeric", "Rosemary", "Paprika")),
    resident_type = factor(resident_type, levels = c("New", "Incumbent")),
    gender = factor(gender, levels = c("Male", "Female")),
    building_type = factor(building_type, levels = c("Male-only", "Female-only", "Co-ed"))
  ) %>%
  dplyr::filter(complete.cases(dplyr::pick(Q1:Q8)))

data_clean$international <- NULL
data_clean$row_id <- 1:nrow(data_clean)
data_clean$mean_score <- rowMeans(data_clean[, paste0("Q", 1:8)])

data_long <- data_clean %>%
  pivot_longer(cols = Q1:Q8, names_to = "question", values_to = "score") %>%
  dplyr::mutate(question = factor(question, levels = paste0("Q", 1:8)))

cat(sprintf("Clean observations: %d\n", nrow(data_clean)))

# ==============================================================================
# SECTION 4: Calculate Similarity to Incumbent
# ==============================================================================

cat("\n=== Calculating Similarity to Incumbent ===\n")

incumbent_profiles <- data_clean %>%
  dplyr::filter(resident_type == "Incumbent") %>%
  dplyr::group_by(building) %>%
  dplyr::summarise(dplyr::across(Q1:Q8, ~ mean(.x, na.rm = TRUE)), n = dplyr::n(), .groups = "drop")

calculate_cosine_similarity <- function(individual_scores, incumbent_scores) {
  if (any(is.na(individual_scores)) || any(is.na(incumbent_scores))) return(NA)
  dot_product <- sum(individual_scores * incumbent_scores)
  norm_ind <- sqrt(sum(individual_scores^2))
  norm_inc <- sqrt(sum(incumbent_scores^2))
  if (norm_ind == 0 || norm_inc == 0) return(NA)
  return(dot_product / (norm_ind * norm_inc) * 100)
}

similarity_results <- lapply(1:nrow(data_clean), function(i) {
  row <- data_clean[i, ]
  bldg <- as.character(row$building)
  inc_profile <- incumbent_profiles %>% dplyr::filter(building == bldg)
  if (nrow(inc_profile) == 0) return(NA)
  individual_scores <- as.numeric(row[paste0("Q", 1:8)])
  incumbent_scores <- as.numeric(inc_profile[1, paste0("Q", 1:8)])
  calculate_cosine_similarity(individual_scores, incumbent_scores)
})

data_clean$similarity <- unlist(similarity_results)
similarity_data <- data_clean %>% dplyr::filter(!is.na(similarity))

# ==============================================================================
# SECTION 5: BUILDING CULTURAL EFFECT ESTIMATION
# ==============================================================================

cat("\n")
cat(strrep("=", 70), "\n")
cat("BUILDING CULTURAL EFFECT ESTIMATION\n")
cat(strrep("=", 70), "\n")

# 5.1 Mixed-Effects Models
model_results <- list()
icc_results <- list()
lrt_results <- list()

for (q in paste0("Q", 1:8)) {
  model_data <- data_long %>% dplyr::filter(question == q)
  
  m_null <- tryCatch({
    suppressMessages(lmer(score ~ 1 + (1 | building), data = model_data, REML = TRUE))
  }, error = function(e) NULL)
  
  m_fixed <- tryCatch({
    lm(score ~ resident_type + gender + month, data = model_data)
  }, error = function(e) NULL)
  
  m_mixed <- tryCatch({
    suppressMessages(lmer(score ~ resident_type + gender + month + (1 | building), 
                          data = model_data, REML = FALSE))
  }, error = function(e) NULL)
  
  if (!is.null(m_null)) {
    var_building <- as.numeric(VarCorr(m_null)$building[1])
    var_residual <- sigma(m_null)^2
    icc <- var_building / (var_building + var_residual)
    
    icc_results[[q]] <- data.frame(
      question = q, var_building = var_building, var_residual = var_residual,
      var_total = var_building + var_residual, ICC = icc
    )
  }
  
  if (!is.null(m_fixed) && !is.null(m_mixed)) {
    ll_fixed <- logLik(m_fixed)
    ll_mixed <- logLik(m_mixed)
    lrt_stat <- max(0, -2 * (as.numeric(ll_fixed) - as.numeric(ll_mixed)))
    lrt_p <- pchisq(lrt_stat, df = 1, lower.tail = FALSE) / 2
    
    lrt_results[[q]] <- data.frame(
      question = q, LRT_stat = lrt_stat, LRT_p = lrt_p,
      AIC_fixed = AIC(m_fixed), AIC_mixed = AIC(m_mixed),
      delta_AIC = AIC(m_fixed) - AIC(m_mixed)
    )
  }
  
  model_results[[q]] <- list(null = m_null, fixed = m_fixed, mixed = m_mixed)
}

icc_df <- bind_rows(icc_results)
lrt_df <- bind_rows(lrt_results)

# 5.2 Overall ICC
m_overall_null <- suppressMessages(
  lmer(mean_score ~ 1 + (1 | building), data = data_clean, REML = TRUE)
)

var_bldg_overall <- as.numeric(VarCorr(m_overall_null)$building[1])
var_res_overall <- sigma(m_overall_null)^2
icc_overall <- var_bldg_overall / (var_bldg_overall + var_res_overall)

cat(sprintf("\nOverall ICC = %.4f (%.1f%% variance)\n", icc_overall, icc_overall * 100))

# 5.3 Building Effects (BLUPs)
building_effects <- list()

for (q in paste0("Q", 1:8)) {
  if (!is.null(model_results[[q]]$mixed)) {
    re <- ranef(model_results[[q]]$mixed)$building
    re$building <- rownames(re)
    re$question <- q
    names(re)[1] <- "effect"
    
    tryCatch({
      re_se <- arm::se.ranef(model_results[[q]]$mixed)$building
      re$se <- re_se[, 1]
    }, error = function(e) {
      pv <- attr(ranef(model_results[[q]]$mixed, condVar = TRUE)$building, "postVar")
      re$se <- sqrt(pv[1,1,])
    })
    
    re$ci_lower <- re$effect - 1.96 * re$se
    re$ci_upper <- re$effect + 1.96 * re$se
    building_effects[[q]] <- re
  }
}

building_effects_df <- bind_rows(building_effects) %>%
  dplyr::mutate(
    building = factor(building, levels = c("Basil", "Turmeric", "Rosemary", "Paprika")),
    question_label = question_labels_short[question]
  )

# 5.4 Bootstrap CI for ICC
cat("\n=== Bootstrap CI for ICC ===\n")

bootstrap_icc <- function(data, indices) {
  d <- data[indices, ]
  tryCatch({
    m <- suppressMessages(lmer(mean_score ~ 1 + (1 | building), data = d, REML = TRUE))
    var_b <- as.numeric(VarCorr(m)$building[1])
    var_r <- sigma(m)^2
    var_b / (var_b + var_r)
  }, error = function(e) NA)
}

cat("Running bootstrap (1000 iterations)...\n")
boot_results <- suppressWarnings(boot(data_clean, bootstrap_icc, R = 1000))

boot_ci <- tryCatch({
  boot.ci(boot_results, type = c("perc", "bca"))
}, error = function(e) {
  boot.ci(boot_results, type = "perc")
})

icc_bootstrap <- data.frame(
  estimate = icc_overall,
  boot_mean = mean(boot_results$t, na.rm = TRUE),
  boot_se = sd(boot_results$t, na.rm = TRUE),
  ci_lower_perc = boot_ci$percent[4],
  ci_upper_perc = boot_ci$percent[5]
)

cat(sprintf("Bootstrap ICC: %.4f [%.4f, %.4f]\n", 
            icc_overall, icc_bootstrap$ci_lower_perc, icc_bootstrap$ci_upper_perc))

# ==============================================================================
# SECTION 6: GENDER INFLUENCE ANALYSIS IN CO-ED BUILDINGS (RQ4)
# ==============================================================================

cat("\n")
cat(strrep("=", 70), "\n")
cat("RQ4: GENDER INFLUENCE ANALYSIS IN CO-ED BUILDINGS\n")
cat(strrep("=", 70), "\n")

# 6.1 Gender-specific incumbent profiles
cat("\n=== 6.1 Gender-Specific Incumbent Profiles ===\n")

coed_incumbent_profiles_by_gender <- data_clean %>%
  dplyr::filter(building_type == "Co-ed", resident_type == "Incumbent") %>%
  dplyr::group_by(building, gender) %>%
  dplyr::summarise(
    dplyr::across(Q1:Q8, ~ mean(.x, na.rm = TRUE)),
    n = dplyr::n(),
    .groups = "drop"
  )

cat("\nIncumbent profiles by building and gender:\n")
print(as.data.frame(coed_incumbent_profiles_by_gender))

# 6.2 Calculate similarity to male and female incumbents
cat("\n=== 6.2 Similarity Calculations ===\n")

coed_new_residents <- data_clean %>%
  dplyr::filter(building_type == "Co-ed", resident_type == "New")

cat(sprintf("Co-ed new residents: %d\n", nrow(coed_new_residents)))
cat(sprintf("  Male: %d\n", sum(coed_new_residents$gender == "Male")))
cat(sprintf("  Female: %d\n", sum(coed_new_residents$gender == "Female")))

gender_influence_results <- lapply(1:nrow(coed_new_residents), function(i) {
  row <- coed_new_residents[i, ]
  bldg <- as.character(row$building)
  own_gender <- as.character(row$gender)
  
  individual_scores <- as.numeric(row[paste0("Q", 1:8)])
  
  male_profile <- coed_incumbent_profiles_by_gender %>%
    dplyr::filter(building == bldg, gender == "Male")
  
  female_profile <- coed_incumbent_profiles_by_gender %>%
    dplyr::filter(building == bldg, gender == "Female")
  
  sim_male <- NA
  sim_female <- NA
  
  if (nrow(male_profile) > 0) {
    male_scores <- as.numeric(male_profile[1, paste0("Q", 1:8)])
    sim_male <- calculate_cosine_similarity(individual_scores, male_scores)
  }
  
  if (nrow(female_profile) > 0) {
    female_scores <- as.numeric(female_profile[1, paste0("Q", 1:8)])
    sim_female <- calculate_cosine_similarity(individual_scores, female_scores)
  }
  
  if (own_gender == "Male") {
    sim_same <- sim_male
    sim_opposite <- sim_female
  } else {
    sim_same <- sim_female
    sim_opposite <- sim_male
  }
  
  data.frame(
    row_id = row$row_id,
    building = bldg,
    new_resident_gender = own_gender,
    month = as.character(row$month),
    sim_male_incumbent = sim_male,
    sim_female_incumbent = sim_female,
    sim_same_gender = sim_same,
    sim_opposite_gender = sim_opposite,
    diff_male_female = sim_male - sim_female,
    diff_same_opposite = sim_same - sim_opposite
  )
})

gender_influence_df <- bind_rows(gender_influence_results) %>%
  dplyr::filter(!is.na(sim_male_incumbent) & !is.na(sim_female_incumbent))

cat(sprintf("\nValid comparisons: %d\n", nrow(gender_influence_df)))

# 6.3 Statistical tests - RELATIVE
cat("\n=== 6.3 Statistical Tests: Same vs Opposite (Relative) ===\n")

overall_ttest_relative <- t.test(gender_influence_df$sim_same_gender, 
                                 gender_influence_df$sim_opposite_gender, 
                                 paired = TRUE)

cat(sprintf("\nOverall: Same=%.2f%%, Opposite=%.2f%%, p=%.4f\n",
            mean(gender_influence_df$sim_same_gender), 
            mean(gender_influence_df$sim_opposite_gender),
            overall_ttest_relative$p.value))

# 6.4 Statistical tests - ABSOLUTE
cat("\n=== 6.4 Statistical Tests: Male vs Female Incumbent (Absolute) ===\n")

overall_ttest_absolute <- t.test(gender_influence_df$sim_male_incumbent, 
                                 gender_influence_df$sim_female_incumbent, 
                                 paired = TRUE)

cat(sprintf("\nOverall: Male inc.=%.2f%%, Female inc.=%.2f%%, p=%.4f\n",
            mean(gender_influence_df$sim_male_incumbent), 
            mean(gender_influence_df$sim_female_incumbent),
            overall_ttest_absolute$p.value))

# 6.5 Building-specific analysis
cat("\n=== 6.5 Building-Specific Analysis ===\n")

rosemary_data <- gender_influence_df %>% dplyr::filter(building == "Rosemary")
paprika_data <- gender_influence_df %>% dplyr::filter(building == "Paprika")

rosemary_ttest_relative <- NULL
rosemary_ttest_absolute <- NULL
paprika_ttest_relative <- NULL
paprika_ttest_absolute <- NULL

if (nrow(rosemary_data) >= 2) {
  rosemary_ttest_relative <- t.test(rosemary_data$sim_same_gender, 
                                    rosemary_data$sim_opposite_gender, paired = TRUE)
  rosemary_ttest_absolute <- t.test(rosemary_data$sim_male_incumbent, 
                                    rosemary_data$sim_female_incumbent, paired = TRUE)
  cat(sprintf("\nROSEMARY (n=%d): Same=%.2f%%, Opp=%.2f%%, p=%.4f\n",
              nrow(rosemary_data), mean(rosemary_data$sim_same_gender), 
              mean(rosemary_data$sim_opposite_gender), rosemary_ttest_relative$p.value))
}

if (nrow(paprika_data) >= 2) {
  paprika_ttest_relative <- t.test(paprika_data$sim_same_gender, 
                                   paprika_data$sim_opposite_gender, paired = TRUE)
  paprika_ttest_absolute <- t.test(paprika_data$sim_male_incumbent, 
                                   paprika_data$sim_female_incumbent, paired = TRUE)
  cat(sprintf("\nPAPRIKA (n=%d): Same=%.2f%%, Opp=%.2f%%, p=%.4f\n",
              nrow(paprika_data), mean(paprika_data$sim_same_gender), 
              mean(paprika_data$sim_opposite_gender), paprika_ttest_relative$p.value))
}

# 6.6 By new resident gender
cat("\n=== 6.6 By New Resident Gender ===\n")

male_new <- gender_influence_df %>% dplyr::filter(new_resident_gender == "Male")
female_new <- gender_influence_df %>% dplyr::filter(new_resident_gender == "Female")

male_ttest <- NULL
female_ttest <- NULL

if (nrow(male_new) >= 2) {
  male_ttest <- t.test(male_new$sim_same_gender, male_new$sim_opposite_gender, paired = TRUE)
  cat(sprintf("\nMale new (n=%d): Same=%.2f%%, Opp=%.2f%%, p=%.4f\n",
              nrow(male_new), mean(male_new$sim_same_gender), 
              mean(male_new$sim_opposite_gender), male_ttest$p.value))
}

if (nrow(female_new) >= 2) {
  female_ttest <- t.test(female_new$sim_same_gender, female_new$sim_opposite_gender, paired = TRUE)
  cat(sprintf("\nFemale new (n=%d): Same=%.2f%%, Opp=%.2f%%, p=%.4f\n",
              nrow(female_new), mean(female_new$sim_same_gender), 
              mean(female_new$sim_opposite_gender), female_ttest$p.value))
}

# 6.7 Summary tables
cat("\n=== 6.7 Summary Tables ===\n")

gender_influence_summary <- gender_influence_df %>%
  dplyr::group_by(new_resident_gender, building) %>%
  dplyr::summarise(
    n = dplyr::n(),
    mean_same = mean(sim_same_gender, na.rm = TRUE),
    sd_same = sd(sim_same_gender, na.rm = TRUE),
    min_same = min(sim_same_gender, na.rm = TRUE),
    max_same = max(sim_same_gender, na.rm = TRUE),
    mean_opposite = mean(sim_opposite_gender, na.rm = TRUE),
    sd_opposite = sd(sim_opposite_gender, na.rm = TRUE),
    min_opposite = min(sim_opposite_gender, na.rm = TRUE),
    max_opposite = max(sim_opposite_gender, na.rm = TRUE),
    mean_diff = mean(diff_same_opposite, na.rm = TRUE),
    mean_male_inc = mean(sim_male_incumbent, na.rm = TRUE),
    mean_female_inc = mean(sim_female_incumbent, na.rm = TRUE),
    .groups = "drop"
  )

cat("\nGender Influence Summary (with min/max):\n")
print(as.data.frame(gender_influence_summary))

# 6.8 Detailed range statistics for each subgroup
cat("\n=== 6.8 Detailed Range Statistics ===\n")

range_stats <- gender_influence_df %>%
  dplyr::group_by(building, new_resident_gender) %>%
  dplyr::summarise(
    n = dplyr::n(),
    same_mean = mean(sim_same_gender),
    same_sd = sd(sim_same_gender),
    same_min = min(sim_same_gender),
    same_max = max(sim_same_gender),
    same_range = max(sim_same_gender) - min(sim_same_gender),
    opp_mean = mean(sim_opposite_gender),
    opp_sd = sd(sim_opposite_gender),
    opp_min = min(sim_opposite_gender),
    opp_max = max(sim_opposite_gender),
    opp_range = max(sim_opposite_gender) - min(sim_opposite_gender),
    .groups = "drop"
  ) %>%
  dplyr::mutate(
    group_label = paste(building, new_resident_gender, sep = "\n")
  )

cat("\nDetailed Range Statistics by Building × Gender:\n")
print(as.data.frame(range_stats[, c("building", "new_resident_gender", "n", 
                                    "same_min", "same_max", "same_range",
                                    "opp_min", "opp_max", "opp_range")]))

# ==============================================================================
# SECTION 7: BUILDING TYPE COMPARISON (RQ5)
# ==============================================================================

cat("\n")
cat(strrep("=", 70), "\n")
cat("RQ5: BUILDING TYPE COMPARISON\n")
cat(strrep("=", 70), "\n")

building_type_scores <- data_long %>%
  dplyr::group_by(building_type, question) %>%
  dplyr::summarise(
    n = dplyr::n(),
    mean = mean(score, na.rm = TRUE),
    sd = sd(score, na.rm = TRUE),
    se = sd / sqrt(n),
    .groups = "drop"
  )

anova_building_type <- list()

for (q in paste0("Q", 1:8)) {
  model_data <- data_long %>% dplyr::filter(question == q)
  aov_result <- aov(score ~ building_type, data = model_data)
  aov_summary <- summary(aov_result)
  tukey_result <- TukeyHSD(aov_result)
  
  anova_building_type[[q]] <- list(
    question = q,
    F_value = aov_summary[[1]]$`F value`[1],
    p_value = aov_summary[[1]]$`Pr(>F)`[1],
    tukey = tukey_result
  )
}

anova_summary_df <- data.frame(
  question = paste0("Q", 1:8),
  question_label = question_labels_short[paste0("Q", 1:8)],
  F_value = sapply(anova_building_type, function(x) x$F_value),
  p_value = sapply(anova_building_type, function(x) x$p_value),
  significant = sapply(anova_building_type, function(x) ifelse(x$p_value < 0.05, "*", ""))
)

# Co-ed comparison
coed_comparison <- list()

for (q in paste0("Q", 1:8)) {
  rosemary_scores <- data_long %>% 
    dplyr::filter(question == q, building == "Rosemary") %>% 
    dplyr::pull(score)
  paprika_scores <- data_long %>% 
    dplyr::filter(question == q, building == "Paprika") %>% 
    dplyr::pull(score)
  
  if (length(rosemary_scores) > 1 && length(paprika_scores) > 1) {
    ttest <- t.test(rosemary_scores, paprika_scores)
    coed_comparison[[q]] <- data.frame(
      question = q,
      rosemary_mean = mean(rosemary_scores),
      paprika_mean = mean(paprika_scores),
      diff = mean(rosemary_scores) - mean(paprika_scores),
      t_value = ttest$statistic,
      p_value = ttest$p.value
    )
  }
}

coed_comparison_df <- bind_rows(coed_comparison)
coed_comparison_df$significant <- ifelse(coed_comparison_df$p_value < 0.05, "*", "")

# ==============================================================================
# SECTION 8: PERMANOVA Analysis
# ==============================================================================

cat("\n=== PERMANOVA Analysis ===\n")

pca_data <- data_clean %>%
  dplyr::filter(complete.cases(dplyr::pick(Q1:Q8)))

clr_transform <- function(x) {
  x_shifted <- x + 0.5
  gm <- exp(mean(log(x_shifted)))
  log(x_shifted / gm)
}

score_matrix <- as.matrix(pca_data[, paste0("Q", 1:8)])
clr_matrix <- t(apply(score_matrix, 1, clr_transform))

aitchison_dist <- dist(clr_matrix, method = "euclidean")
pcoa_aitchison <- cmdscale(aitchison_dist, k = 2, eig = TRUE)

pcoa_coords <- as.data.frame(pcoa_aitchison$points)
colnames(pcoa_coords) <- c("PCoA1", "PCoA2")
pcoa_coords <- cbind(pca_data[, c("building", "gender", "resident_type", "month", "building_type")], 
                     pcoa_coords)

var_explained_aitchison <- round(pcoa_aitchison$eig / sum(abs(pcoa_aitchison$eig)) * 100, 2)

permanova_building <- adonis2(aitchison_dist ~ building + gender + resident_type,
                              data = pca_data, permutations = 999)

cat("\nPERMANOVA (Building):\n")
print(permanova_building)

# ==============================================================================
# SECTION 9: VISUALIZATION
# Figure 1 is reserved for dormitory photos (manual insertion)
# Analysis figures start from Figure 2
# ==============================================================================

cat("\n")
cat(strrep("=", 70), "\n")
cat("CREATING PUBLICATION-READY FIGURES\n")
cat("Figure 1: Dormitory Photos (manual insertion - not generated here)\n")
cat("Figure 2+: Analysis results\n")
cat(strrep("=", 70), "\n")

dir.create("figures", showWarnings = FALSE)

# -----------------------------------------------------------------------------
# Figure 2: Building Cultural Effect Estimation (ICC, Bootstrap, PCoA)
# Corresponds to manuscript Figure 2 (fig:icc)
# -----------------------------------------------------------------------------

cat("\n  Creating Figure 2: Building Cultural Effect Estimation...\n")

p_fig2a <- ggplot(icc_df, aes(x = reorder(question, -ICC), y = ICC)) +
  geom_bar(stat = "identity", fill = "#4393C3", alpha = 0.8, color = "black", linewidth = 0.3) +
  geom_hline(yintercept = icc_overall, linetype = "dashed", color = "red", linewidth = 1) +
  annotate("text", x = 7, y = icc_overall + 0.02, 
           label = sprintf("Overall ICC = %.3f", icc_overall),
           color = "red", fontface = "bold", size = 3.5) +
  scale_y_continuous(labels = scales::percent_format(), limits = c(0, max(icc_df$ICC) * 1.2)) +
  labs(x = "Question", y = "ICC", title = "a) ICC by Question") +
  theme_nature()

boot_df <- data.frame(ICC = boot_results$t[!is.na(boot_results$t)])

p_fig2b <- ggplot(boot_df, aes(x = ICC)) +
  geom_histogram(aes(y = after_stat(density)), bins = 40, 
                 fill = "#4393C3", color = "white", alpha = 0.7) +
  geom_density(linewidth = 1, color = "#D6604D") +
  geom_vline(xintercept = icc_overall, linetype = "solid", color = "black", linewidth = 1) +
  geom_vline(xintercept = icc_bootstrap$ci_lower_perc, linetype = "dashed", color = "red") +
  geom_vline(xintercept = icc_bootstrap$ci_upper_perc, linetype = "dashed", color = "red") +
  labs(x = "ICC", y = "Density",
       title = sprintf("b) Bootstrap (95%% CI: [%.3f, %.3f])", 
                       icc_bootstrap$ci_lower_perc, icc_bootstrap$ci_upper_perc)) +
  theme_nature()

centroids <- pcoa_coords %>%
  dplyr::group_by(building) %>%
  dplyr::summarise(PCoA1 = mean(PCoA1), PCoA2 = mean(PCoA2), .groups = "drop")

p_fig2c <- ggplot(pcoa_coords, aes(x = PCoA1, y = PCoA2)) +
  stat_ellipse(aes(color = building, fill = building), 
               geom = "polygon", alpha = 0.15, level = 0.95, linewidth = 0.8) +
  geom_point(aes(color = building, shape = resident_type), size = 2, alpha = 0.6) +
  geom_point(data = centroids, aes(fill = building), 
             shape = 21, size = 4, color = "black", stroke = 1) +
  annotate("text", x = -Inf, y = Inf, 
           label = sprintf("PERMANOVA\nBuilding: R2=%.3f, p=%.3f", 
                           permanova_building$R2[1], permanova_building$`Pr(>F)`[1]),
           hjust = -0.05, vjust = 1.5, size = 3, fontface = "bold") +
  scale_color_manual(values = building_colors) +
  scale_fill_manual(values = building_colors) +
  scale_shape_manual(values = c("New" = 16, "Incumbent" = 17)) +
  labs(x = sprintf("PCoA1 (%.1f%%)", var_explained_aitchison[1]),
       y = sprintf("PCoA2 (%.1f%%)", var_explained_aitchison[2]),
       title = "c) PCoA (Aitchison Distance)") +
  theme_nature() + coord_fixed()

fig2 <- (p_fig2a + p_fig2b) / p_fig2c +
  plot_layout(heights = c(1, 1.2)) +
  plot_annotation(title = "Figure 2: Building Cultural Effect Estimation")

ggsave("figures/fig2_cultural_effects.pdf", fig2, width = 14, height = 10, dpi = 300)
ggsave("figures/fig2_cultural_effects.png", fig2, width = 14, height = 10, dpi = 300)
cat("  Saved: Figure 2 (fig2_cultural_effects.pdf/png)\n")

# -----------------------------------------------------------------------------
# Figure 3: Cultural Convergence Analysis
# Corresponds to manuscript Figure 3 (fig:convergence)
# -----------------------------------------------------------------------------

cat("  Creating Figure 3: Cultural Convergence...\n")

p_fig3a <- ggplot(similarity_data, aes(x = building, y = similarity, fill = building)) +
  geom_violin(trim = FALSE, alpha = 0.6, color = NA) +
  geom_boxplot(width = 0.2, outlier.shape = NA, alpha = 0.9, color = "black") +
  scale_fill_manual(values = building_colors) +
  labs(x = "Building", y = "Similarity to Incumbent (%)", title = "a) Similarity by Building") +
  theme_nature() + theme(legend.position = "none")

p_fig3b <- ggplot(similarity_data, aes(x = resident_type, y = similarity, fill = resident_type)) +
  geom_violin(trim = FALSE, alpha = 0.6, color = NA) +
  geom_boxplot(width = 0.2, outlier.shape = NA, alpha = 0.9, color = "black") +
  facet_wrap(~ building, nrow = 1) +
  stat_compare_means(method = "wilcox.test", label = "p.format", label.y = 102) +
  scale_fill_manual(values = resident_colors) +
  labs(x = "Resident Type", y = "Similarity (%)", title = "b) By Resident Type") +
  theme_nature() + theme(legend.position = "bottom")

temporal_sim <- similarity_data %>%
  dplyr::group_by(month, resident_type) %>%
  dplyr::summarise(mean_sim = mean(similarity), se = sd(similarity)/sqrt(dplyr::n()), 
                   n = dplyr::n(), .groups = "drop")

p_fig3c <- ggplot(temporal_sim, aes(x = month, y = mean_sim, color = resident_type, group = resident_type)) +
  geom_line(linewidth = 1) +
  geom_point(size = 3) +
  geom_errorbar(aes(ymin = mean_sim - 1.96*se, ymax = mean_sim + 1.96*se), width = 0.15) +
  scale_color_manual(values = resident_colors) +
  labs(x = "Month", y = "Mean Similarity (%)", title = "c) Temporal Convergence",
       color = "Resident Type") +
  theme_nature() + theme(legend.position = "bottom")

fig3 <- (p_fig3a + p_fig3b + p_fig3c) +
  plot_layout(ncol = 3) +
  plot_annotation(title = "Figure 3: Cultural Convergence Analysis")

ggsave("figures/fig3_convergence.pdf", fig3, width = 16, height = 5, dpi = 300)
ggsave("figures/fig3_convergence.png", fig3, width = 16, height = 5, dpi = 300)
cat("  Saved: Figure 3 (fig3_convergence.pdf/png)\n")

# -----------------------------------------------------------------------------
# Figure 4: Gender Influence Detailed Analysis (4-panel)
# Corresponds to manuscript Figure 4 (fig:gender_detail)
# -----------------------------------------------------------------------------

cat("  Creating Figure 4: Gender Influence Detailed Analysis...\n")

# Prepare data for paired comparison plot
gender_influence_long_relative <- gender_influence_df %>%
  pivot_longer(cols = c(sim_same_gender, sim_opposite_gender),
               names_to = "influence_type", values_to = "similarity") %>%
  dplyr::mutate(influence_type = factor(influence_type, 
                                        levels = c("sim_same_gender", "sim_opposite_gender"),
                                        labels = c("Same-gender", "Opposite-gender")))

# Fig 4a: Individual Paired Comparisons
paired_data <- gender_influence_df %>%
  dplyr::mutate(
    individual_id = row_number(),
    slope_direction = ifelse(sim_same_gender > sim_opposite_gender, "Same higher", "Opposite higher")
  )

p_fig4a <- ggplot(paired_data, aes(x = 1, xend = 2)) +
  geom_segment(aes(y = sim_same_gender, yend = sim_opposite_gender, 
                   color = slope_direction, group = individual_id),
               alpha = 0.5, linewidth = 0.5) +
  geom_point(aes(x = 1, y = sim_same_gender), color = influence_colors["Same-gender"], 
             size = 2, alpha = 0.7) +
  geom_point(aes(x = 2, y = sim_opposite_gender), color = influence_colors["Opposite-gender"], 
             size = 2, alpha = 0.7) +
  facet_wrap(~ building) +
  scale_x_continuous(breaks = c(1, 2), labels = c("Same-\ngender", "Opposite-\ngender"),
                     limits = c(0.5, 2.5)) +
  scale_color_manual(values = c("Same higher" = "#2166AC", "Opposite higher" = "#B2182B"),
                     name = "Direction") +
  labs(x = "", y = "Cosine Similarity (%)", 
       title = "a) Individual Paired Comparisons") +
  theme_nature() +
  theme(legend.position = "bottom")

# Fig 4b: Distribution of Similarity Differences
p_fig4b <- ggplot(gender_influence_df, aes(x = diff_same_opposite, fill = building)) +
  geom_histogram(bins = 15, alpha = 0.7, position = "identity", color = "black", linewidth = 0.3) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "red", linewidth = 1) +
  facet_wrap(~ building, ncol = 1, scales = "free_y") +
  scale_fill_manual(values = building_colors[c("Rosemary", "Paprika")]) +
  labs(x = "Similarity Difference (Same - Opposite Gender)", y = "Count",
       title = "b) Distribution of Similarity Differences") +
  theme_nature() +
  theme(legend.position = "none")

# Fig 4c: Influence Matrix (Heatmap)
influence_matrix_data <- gender_influence_df %>%
  dplyr::group_by(building, new_resident_gender) %>%
  dplyr::summarise(
    Same_gender = mean(sim_same_gender),
    Opposite_gender = mean(sim_opposite_gender),
    .groups = "drop"
  ) %>%
  pivot_longer(cols = c(Same_gender, Opposite_gender),
               names_to = "influence_type", values_to = "similarity") %>%
  dplyr::mutate(
    group = paste(building, new_resident_gender, sep = "\n"),
    influence_type = factor(influence_type, levels = c("Same_gender", "Opposite_gender"),
                            labels = c("Same-gender\nIncumbent", "Opposite-gender\nIncumbent"))
  )

p_fig4c <- ggplot(influence_matrix_data, aes(x = influence_type, y = group, fill = similarity)) +
  geom_tile(color = "white", linewidth = 0.5) +
  geom_text(aes(label = sprintf("%.1f%%", similarity)), color = "black", size = 4) +
  scale_fill_gradient2(low = "#B2182B", mid = "#F7F7F7", high = "#2166AC", 
                       midpoint = 95, limits = c(90, 100),
                       name = "Similarity (%)") +
  labs(x = "Incumbent Type", y = "New Resident (Building × Gender)",
       title = "c) Influence Matrix") +
  theme_nature() +
  theme(axis.text.x = element_text(angle = 0))

# Fig 4d: Effect Sizes with 95% CI
effect_size_data <- data.frame(
  group = c("Overall", "Male New", "Female New", "Rosemary", "Paprika"),
  mean_diff = c(
    mean(gender_influence_df$diff_same_opposite),
    mean(male_new$diff_same_opposite),
    mean(female_new$diff_same_opposite),
    mean(rosemary_data$diff_same_opposite),
    mean(paprika_data$diff_same_opposite)
  ),
  se = c(
    sd(gender_influence_df$diff_same_opposite) / sqrt(nrow(gender_influence_df)),
    sd(male_new$diff_same_opposite) / sqrt(nrow(male_new)),
    sd(female_new$diff_same_opposite) / sqrt(nrow(female_new)),
    sd(rosemary_data$diff_same_opposite) / sqrt(nrow(rosemary_data)),
    sd(paprika_data$diff_same_opposite) / sqrt(nrow(paprika_data))
  ),
  n = c(nrow(gender_influence_df), nrow(male_new), nrow(female_new), 
        nrow(rosemary_data), nrow(paprika_data))
)
effect_size_data$ci_lower <- effect_size_data$mean_diff - 1.96 * effect_size_data$se
effect_size_data$ci_upper <- effect_size_data$mean_diff + 1.96 * effect_size_data$se
effect_size_data$group <- factor(effect_size_data$group, 
                                 levels = c("Overall", "Male New", "Female New", "Rosemary", "Paprika"))

p_fig4d <- ggplot(effect_size_data, aes(x = group, y = mean_diff)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red", linewidth = 1) +
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper), size = 0.8, linewidth = 1) +
  geom_text(aes(label = sprintf("n=%d", n)), vjust = -1.5, size = 3) +
  labs(x = "Subgroup", y = "Mean Difference (Same - Opposite)\nwith 95% CI",
       title = "d) Effect Sizes by Subgroup") +
  theme_nature() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

fig4 <- (p_fig4a + p_fig4b) / (p_fig4c + p_fig4d) +
  plot_layout(heights = c(1, 1)) +
  plot_annotation(title = "Figure 4: Gender Influence Detailed Analysis")

ggsave("figures/fig4_gender_influence_detail.pdf", fig4, width = 14, height = 12, dpi = 300)
ggsave("figures/fig4_gender_influence_detail.png", fig4, width = 14, height = 12, dpi = 300)
cat("  Saved: Figure 4 (fig4_gender_influence_detail.pdf/png)\n")

# -----------------------------------------------------------------------------
# Figure 5: Building Type Comparison (Q5, Q8, Co-ed)
# Corresponds to manuscript Figure 5 (fig:building_type)
# -----------------------------------------------------------------------------

cat("  Creating Figure 5: Building Type Comparison...\n")

q5_data <- data_long %>% dplyr::filter(question == "Q5")

p_fig5a <- ggplot(q5_data, aes(x = building_type, y = score, fill = building_type)) +
  geom_violin(trim = FALSE, alpha = 0.6, color = NA) +
  geom_boxplot(width = 0.2, outlier.shape = NA, alpha = 0.9, color = "black") +
  stat_compare_means(comparisons = list(c("Male-only", "Co-ed"), 
                                        c("Female-only", "Co-ed"),
                                        c("Male-only", "Female-only")),
                     method = "t.test", label = "p.signif") +
  scale_fill_manual(values = building_type_colors) +
  labs(x = "Building Type", y = "Score", title = "a) Q5: Event Interest") +
  theme_nature() + theme(legend.position = "none")

q8_data <- data_long %>% dplyr::filter(question == "Q8")

p_fig5b <- ggplot(q8_data, aes(x = building_type, y = score, fill = building_type)) +
  geom_violin(trim = FALSE, alpha = 0.6, color = NA) +
  geom_boxplot(width = 0.2, outlier.shape = NA, alpha = 0.9, color = "black") +
  stat_compare_means(comparisons = list(c("Male-only", "Co-ed"), 
                                        c("Female-only", "Co-ed"),
                                        c("Male-only", "Female-only")),
                     method = "t.test", label = "p.signif") +
  scale_fill_manual(values = building_type_colors) +
  labs(x = "Building Type", y = "Score", title = "b) Q8: Building Attachment") +
  theme_nature() + theme(legend.position = "none")

coed_long <- data_long %>% dplyr::filter(building %in% c("Rosemary", "Paprika"))
sig_questions <- coed_comparison_df %>% dplyr::filter(p_value < 0.05) %>% dplyr::pull(question)

if (length(sig_questions) > 0) {
  p_fig5c <- ggplot(coed_long %>% dplyr::filter(question %in% sig_questions), 
                    aes(x = question, y = score, fill = building)) +
    geom_boxplot(position = position_dodge(0.8), alpha = 0.8, color = "black", linewidth = 0.3) +
    scale_fill_manual(values = c("Rosemary" = "#9467BD", "Paprika" = "#D62728")) +
    scale_x_discrete(labels = question_labels_short[sig_questions]) +
    labs(x = "Question", y = "Score", title = "c) Rosemary vs Paprika", fill = "Building") +
    theme_nature() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1), legend.position = "bottom")
} else {
  p_fig5c <- ggplot() + 
    annotate("text", x = 0.5, y = 0.5, label = "No significant differences", size = 5) +
    labs(title = "c) Rosemary vs Paprika") + theme_nature()
}

fig5 <- (p_fig5a + p_fig5b + p_fig5c) +
  plot_layout(ncol = 3) +
  plot_annotation(title = "Figure 5: Building Type Comparison")

ggsave("figures/fig5_building_type_comparison.pdf", fig5, width = 15, height = 5, dpi = 300)
ggsave("figures/fig5_building_type_comparison.png", fig5, width = 15, height = 5, dpi = 300)
cat("  Saved: Figure 5 (fig5_building_type_comparison.pdf/png)\n")

# -----------------------------------------------------------------------------
# Figure 6: Q2 Opposite-Sex Communication Barrier Analysis
# Corresponds to manuscript Figure 6 (fig:q2_barrier)
# -----------------------------------------------------------------------------

cat("  Creating Figure 6: Q2 Barrier Analysis...\n")

q2_data <- data_long %>% dplyr::filter(question == "Q2")

# Fig 6a: Q2 by Building and Gender
p_fig6a <- ggplot(q2_data, aes(x = building, y = score, fill = gender)) +
  geom_boxplot(position = position_dodge(0.8), alpha = 0.8, color = "black", linewidth = 0.3) +
  geom_jitter(aes(color = gender), position = position_jitterdodge(jitter.width = 0.15, dodge.width = 0.8),
              size = 1.5, alpha = 0.5) +
  scale_fill_manual(values = gender_colors) +
  scale_color_manual(values = gender_colors) +
  labs(x = "Building", y = "Q2 Score (Opp. Sex Barrier)", 
       title = "a) Q2 by Building and Gender",
       fill = "Gender", color = "Gender") +
  theme_nature() +
  theme(legend.position = "bottom")

# Fig 6b: Temporal change in Co-ed buildings
q2_coed_temporal <- data_long %>%
  dplyr::filter(question == "Q2", building %in% c("Rosemary", "Paprika")) %>%
  dplyr::group_by(building, gender, month) %>%
  dplyr::summarise(
    mean_score = mean(score, na.rm = TRUE),
    se = sd(score, na.rm = TRUE) / sqrt(dplyr::n()),
    n = dplyr::n(),
    .groups = "drop"
  )

p_fig6b <- ggplot(q2_coed_temporal, aes(x = month, y = mean_score, color = gender, 
                                        group = interaction(building, gender))) +
  geom_line(aes(linetype = building), linewidth = 1) +
  geom_point(aes(size = n), alpha = 0.8) +
  geom_errorbar(aes(ymin = mean_score - se, ymax = mean_score + se), width = 0.15) +
  scale_color_manual(values = gender_colors) +
  scale_linetype_manual(values = c("Rosemary" = "solid", "Paprika" = "dashed")) +
  labs(x = "Month", y = "Mean Q2 Score", 
       title = "b) Temporal Change in Co-ed Buildings",
       color = "Gender", linetype = "Building", size = "n") +
  theme_nature() +
  theme(legend.position = "bottom", legend.box = "horizontal")

fig6 <- (p_fig6a + p_fig6b) +
  plot_layout(ncol = 2) +
  plot_annotation(title = "Figure 6: Q2 Opposite-Sex Communication Barrier Analysis")

ggsave("figures/fig6_q2_barrier.pdf", fig6, width = 14, height = 6, dpi = 300)
ggsave("figures/fig6_q2_barrier.png", fig6, width = 14, height = 6, dpi = 300)
cat("  Saved: Figure 6 (fig6_q2_barrier.pdf/png)\n")

# -----------------------------------------------------------------------------
# Figure 7: Building Type Overview
# Corresponds to manuscript Figure 7 (fig:overview)
# -----------------------------------------------------------------------------

cat("  Creating Figure 7: Building Type Overview...\n")

sample_dist <- data_clean %>%
  dplyr::count(building_type, gender, resident_type) %>%
  dplyr::mutate(label = paste0("n=", n))

p_fig7a <- ggplot(sample_dist, aes(x = building_type, y = n, fill = interaction(gender, resident_type))) +
  geom_bar(stat = "identity", position = "dodge", alpha = 0.8, color = "black", linewidth = 0.3) +
  geom_text(aes(label = n), position = position_dodge(0.9), vjust = -0.5, size = 3) +
  scale_fill_manual(values = c("Male.New" = "#6BAED6", "Male.Incumbent" = "#08519C",
                               "Female.New" = "#FC9272", "Female.Incumbent" = "#A50F15"),
                    labels = c("Male New", "Male Incumbent", "Female New", "Female Incumbent")) +
  labs(x = "Building Type", y = "Count", fill = NULL, title = "a) Sample Distribution") +
  theme_nature() +
  theme(legend.position = "bottom", legend.direction = "horizontal")

p_fig7b <- ggplot(building_type_scores, aes(x = question, y = mean, fill = building_type)) +
  geom_bar(stat = "identity", position = position_dodge(0.8), width = 0.7, 
           alpha = 0.8, color = "black", linewidth = 0.3) +
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), 
                position = position_dodge(0.8), width = 0.2) +
  scale_fill_manual(values = building_type_colors) +
  scale_x_discrete(labels = question_labels_short) +
  labs(x = "Question", y = "Mean Score (1-5)", fill = "Building Type",
       title = "b) Question Scores by Building Type") +
  theme_nature() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), legend.position = "bottom")

anova_summary_df$effect_size <- -log10(pmax(anova_summary_df$p_value, 1e-10))
anova_summary_df$sig_label <- ifelse(anova_summary_df$p_value < 0.001, "***",
                                     ifelse(anova_summary_df$p_value < 0.01, "**",
                                            ifelse(anova_summary_df$p_value < 0.05, "*", "")))

p_fig7c <- ggplot(anova_summary_df, aes(x = reorder(question_label, -F_value), y = F_value)) +
  geom_bar(stat = "identity", fill = "#756BB1", alpha = 0.8, color = "black", linewidth = 0.3) +
  geom_hline(yintercept = qf(0.95, 2, nrow(data_long)/8 - 3), linetype = "dashed", color = "red") +
  geom_text(aes(label = sig_label), vjust = -0.5, size = 5) +
  labs(x = "Question", y = "F-statistic", title = "c) Building Type Effect (ANOVA)") +
  theme_nature() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

fig7 <- (p_fig7a + p_fig7b + p_fig7c) +
  plot_layout(ncol = 3, widths = c(1, 1.5, 1)) +
  plot_annotation(title = "Figure 7: Building Type Overview")

ggsave("figures/fig7_building_type_overview.pdf", fig7, width = 16, height = 5, dpi = 300)
ggsave("figures/fig7_building_type_overview.png", fig7, width = 16, height = 5, dpi = 300)
cat("  Saved: Figure 7 (fig7_building_type_overview.pdf/png)\n")

# ==============================================================================
# SECTION 10: Save Tables
# ==============================================================================

cat("\n=== Saving Tables ===\n")

write_csv(data_clean %>% dplyr::count(building, building_type, gender, resident_type), 
          "figures/table1_sample_sizes.csv")
write_csv(icc_df, "figures/table2_icc_results.csv")
write_csv(building_effects_df, "figures/table3_building_effects.csv")
write_csv(gender_influence_summary, "figures/table4_gender_influence.csv")
write_csv(anova_summary_df, "figures/table5_building_type_anova.csv")
write_csv(coed_comparison_df, "figures/table6_coed_comparison.csv")

permanova_table <- data.frame(
  Factor = rownames(permanova_building)[1:3],
  Df = permanova_building$Df[1:3],
  R2 = round(permanova_building$R2[1:3], 4),
  F_value = round(permanova_building$F[1:3], 3),
  P_value = permanova_building$`Pr(>F)`[1:3]
)
write_csv(permanova_table, "figures/table7_permanova.csv")

write_csv(range_stats, "figures/table8_gender_building_range.csv")

effect_size_output <- data.frame(
  group = c("Overall", "Male New", "Female New", "Rosemary", "Paprika"),
  diff = c(
    mean(gender_influence_df$diff_same_opposite),
    mean(male_new$diff_same_opposite),
    mean(female_new$diff_same_opposite),
    mean(rosemary_data$diff_same_opposite),
    mean(paprika_data$diff_same_opposite)
  ),
  se = c(
    sd(gender_influence_df$diff_same_opposite) / sqrt(nrow(gender_influence_df)),
    sd(male_new$diff_same_opposite) / sqrt(nrow(male_new)),
    sd(female_new$diff_same_opposite) / sqrt(nrow(female_new)),
    sd(rosemary_data$diff_same_opposite) / sqrt(nrow(rosemary_data)),
    sd(paprika_data$diff_same_opposite) / sqrt(nrow(paprika_data))
  ),
  p_value = c(
    overall_ttest_relative$p.value,
    ifelse(!is.null(male_ttest), male_ttest$p.value, NA),
    ifelse(!is.null(female_ttest), female_ttest$p.value, NA),
    ifelse(!is.null(rosemary_ttest_relative), rosemary_ttest_relative$p.value, NA),
    ifelse(!is.null(paprika_ttest_relative), paprika_ttest_relative$p.value, NA)
  )
)
write_csv(effect_size_output, "figures/table9_effect_sizes.csv")

cat("  All tables saved\n")

# ==============================================================================
# SECTION 11: Final Summary
# ==============================================================================

cat("\n")
cat(strrep("=", 70), "\n")
cat("ANALYSIS COMPLETE - FINAL SUMMARY\n")
cat(strrep("=", 70), "\n")

cat("\n1. DATA:\n")
cat(sprintf("   Total: %d observations, Co-ed new: %d\n", nrow(data_clean), nrow(gender_influence_df)))

cat("\n2. BUILDING EFFECT:\n")
cat(sprintf("   ICC: %.4f [%.4f, %.4f]\n", icc_overall, icc_bootstrap$ci_lower_perc, icc_bootstrap$ci_upper_perc))
cat(sprintf("   PERMANOVA: R2=%.4f, p=%.4f\n", permanova_building$R2[1], permanova_building$`Pr(>F)`[1]))

cat("\n3. GENDER INFLUENCE (Relative):\n")
cat(sprintf("   Same: %.2f%%, Opposite: %.2f%%, p=%.4f\n",
            mean(gender_influence_df$sim_same_gender), 
            mean(gender_influence_df$sim_opposite_gender),
            overall_ttest_relative$p.value))

cat("\n4. GENDER INFLUENCE (Absolute):\n")
cat(sprintf("   Male inc.: %.2f%%, Female inc.: %.2f%%, p=%.4f\n",
            mean(gender_influence_df$sim_male_incumbent), 
            mean(gender_influence_df$sim_female_incumbent),
            overall_ttest_absolute$p.value))

cat("\n5. RANGE BY GENDER × BUILDING:\n")
for (i in 1:nrow(range_stats)) {
  cat(sprintf("   %s %s (n=%d): Same %.1f-%.1f%%, Opp %.1f-%.1f%%\n",
              range_stats$building[i], range_stats$new_resident_gender[i], range_stats$n[i],
              range_stats$same_min[i], range_stats$same_max[i],
              range_stats$opp_min[i], range_stats$opp_max[i]))
}

cat("\n")
cat(strrep("=", 70), "\n")
cat("FIGURE-CODE MAPPING (Figure 1 = Dormitory Photos, not generated)\n")
cat(strrep("=", 70), "\n")
cat("\n")
cat("Figure 1: Dormitory Photos (manual insertion - not generated by R)\n")
cat("Figure 2: fig2_cultural_effects.pdf/png - ICC, Bootstrap, PCoA\n")
cat("Figure 3: fig3_convergence.pdf/png - Cultural Convergence\n")
cat("Figure 4: fig4_gender_influence_detail.pdf/png - Gender Influence 4-panel\n")
cat("Figure 5: fig5_building_type_comparison.pdf/png - Q5, Q8, Co-ed comparison\n")
cat("Figure 6: fig6_q2_barrier.pdf/png - Q2 Barrier Analysis\n")
cat("Figure 7: fig7_building_type_overview.pdf/png - Building Type Overview\n")
cat("\n")
cat("Tables: table1-9_*.csv\n")
cat(strrep("=", 70), "\n")
